- name: Run marood Bot
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: python tal22_encrypted.py # تشغيل الملف المشفر الجديد
